### ISSUE TITLE
Unable to implement on red-vs-ared.cc

### ISSUE THREAD

**Issue by Horopter** [bhattmansi/Implementation-of-CARED-in-ns3#1]
Hello,
I've tried implementing your code by modifying the red-vs-ared.cc example to check if the emulation really works. However, I am getting the following error.
`‘m_stats’ was not declared in this scope`
`   return m_stats;`
     `          ^`

Please upload the necessary docs for testing against existing RED adaptations.

**Comment by bhattmansi** [comment]
Hi,
i will try to fix the issue as soon as possible.
