### ISSUE TITLE
Delete new files that got added in the latest commit

### ISSUE THREAD

**Issue by mohittahiliani** [bhattmansi/Implementation-of-CARED-in-ns3#2]
The latest commit 'Sync with dev' has messed up the repo.

First thing, please remove the following folders from the github repo (you can keep them in your local repo if you wish)

![screen shot 2017-11-03 at 09 56 08](https://user-images.githubusercontent.com/3018687/32360598-72e23c60-c07d-11e7-9f7e-ae5be394b0f4.png)

**Comment by mohittahiliani** [comment]
@bhattmansi - Close the issue after it has been resolved. Otherwise we may forget which ones are done and which are pending.

I can still see those unwanted files in your repo.

**Comment by bhattmansi** [comment]
sir
when i am deleting those files compilation is not happeing

after deleting bindings/python

it is showing error in the compilation
